[package]
name = "ascii-ipa"
version = "2.0.0"
entrypoint = "src/main.typ"
authors = ["imatpot"]
license = "MIT"
description = "Converter for ASCII representations of the International Phonetic Alphabet (IPA)"
repository = "https://github.com/imatpot/typst-packages"
keywords = ["ascii", "ipa", "linguistics", "phonetics", "phonology", "branner", "praat", "sil", "x-sampa", "xsampa"]
compiler = "0.10.0"
exclude = ["test"]
